#!/usr/bin/env python
import argparse
import json
import os

home = os.environ.get('HOME')
def change_number(num):
    with open(home + "/Code/scripts/data.json") as data_file:
        data = json.load(data_file)
        data["number"] = num
    with open(home + "/Code/scripts/data.json", "w") as write_file:
        json.dump(data, write_file)

parser = argparse.ArgumentParser()
parser.add_argument("-n", "--next", action="store_true", help="changes to the next background immediately")
parser.add_argument("-r", "--repeat", type=int, help="set the number of days you want a specific background to display")
args = parser.parse_args()

if args.next:
    change_number(3)
    os.system('python $HOME/Code/scripts/feh.py')

if args.repeat and args.repeat > 0:
    change_number(args.repeat)
